version: '3'

services:
  postgres:
    container_name: db
    image: postgres:14
    ports:
      - 5434:5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
volumes:
  postgres_data:
