default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  port: 5434
  username: postgres
  password: password

development:
  <<: *default
  database: tasks_dev

test:
  <<: *default
  database: tasks_test

production:
  <<: *default
  database: tasks_production
  username: auth
  password: <%= ENV["TASKS_DATABASE_PASSWORD"] %>
